title: pico-jxgLABO
description: A command-line interface for Raspberry Pi Pico to control GPIO, ADC, PWM, I2C, and SPI functionalities
remote_theme: "minima"
baseurl: "/pico-jxgLABO"
url: "https://ypsitau.github.io/pico-jxgLABO"
